export const constants = {
  // Videos
  INITIALISE_VIDEOS: "INITIALISE_VIDEOS",

  // Playlist
  INITIALISE_PLAYLISTS: "INITIALISE_PLAYLISTS",
  UPDATE_PLAYLISTS: "UPDATE_PLAYLISTS",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  TOGGLE_PLAYLIST_VIDEO: "TOGGLE_PLAYLIST_VIDEO",

  // Playlist Modal
  OPEN_P_MODAL: "OPEN_P_MODAL",
  CLOSE_P_MODAL: "CLOSE_P_MODAL",

  // Likes
  TOGGLE_LIKE: "TOGGLE_LIKE",
};
